listen:
  hostname: '0.0.0.0'
  port: 9000

# Correspond to your reverse proxy server_name/listen configuration (i.e., your public PeerTube instance URL)
webserver:
  https: true
  hostname: undefined
  port: 443

rates_limit:
  api:
    window: 10 seconds
    max: 999
  login:
    window: 10 seconds
    max: 999
  signup:
    window: 10 seconds
    max: 999
  ask_send_email:
    window: 10 seconds
    max: 999
  receive_client_log:
    window: 10 seconds
    max: 999
  plugins:
    window: 10 seconds
    max: 999
  well_known:
    window: 10 seconds
    max: 999
  feeds:
    window: 10 seconds
    max: 999
  activity_pub:
    window: 10 seconds
    max: 999
  client:
    window: 10 seconds
    max: 999

# Proxies to trust to get real client IP
# If you run PeerTube just behind a local proxy (nginx), keep 'loopback'
# If you run PeerTube behind a remote proxy, add the proxy IP address (or subnet)
trust_proxy:
  - 'loopback'
  - 'linklocal'
  - 'uniquelocal'

# Your database name will be database.name OR 'peertube'+database.suffix
database:
  hostname: 'postgres'
  port: 5432
  ssl: false
  suffix: ''
  username: 'postgres'
  password: 'postgres'

# Redis server for short time storage
redis:
  hostname: 'redis'
  port: 6379
  auth: null

# From the project root directory
storage:
  tmp: '../data/tmp/' # Use to download data (imports etc), store uploaded files before and during processing...
  tmp_persistent: '../data/tmp-persistent/' # As tmp but the directory is not cleaned up between PeerTube restarts
  bin: '../data/bin/'
  avatars: '../data/avatars/'
  web_videos: '../data/web-videos/'
  streaming_playlists: '../data/streaming-playlists'
  redundancy: '../data/redundancy/'
  logs: '../data/logs/'
  previews: '../data/previews/'
  thumbnails: '../data/thumbnails/'
  storyboards: '../data/storyboards/'
  torrents: '../data/torrents/'
  captions: '../data/captions/'
  cache: '../data/cache/'
  plugins: '../data/plugins/'
  well_known: '../data/well-known/'
  # Overridable client files in client/dist/assets/images :
  # - logo.svg
  # - favicon.png
  # - default-playlist.jpg
  # - default-avatar-account.png
  # - default-avatar-video-channel.png
  # - and icons/*.png (PWA)
  # Could contain for example assets/images/favicon.png
  # If the file exists, peertube will serve it
  # If not, peertube will fallback to the default fil
  client_overrides: '../data/client-overrides/'


object_storage:
  upload_acl:
    public: null # Set to null here because we can't using env variables
    private: null

log:
  level: 'info' # 'debug' | 'info' | 'warn' | 'error'

tracker:
  enabled: true
  reject_too_many_announces: false # false because we have issues with docker ws ip/port forwarding

admin:
  email: null
